v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
B 2 60 160 860 560 {flags=graph
y1=0.66875437
y2=0.69818539
ypos1=-0.11
ypos2=2
divy=5
subdivy=4
unity=1
x1=4.3066451e-06
x2=4.9079404e-06
divx=5
subdivx=1
xlabmag=1.0
ylabmag=1.0


dataset=-1
unitx=1
logx=0
logy=0

digital=0


sim_type=tran




color="4 5"
node="x1.vdac_p
x1.vdac_n"}
B 2 890 160 1690 560 {flags=graph
y1=0
y2=2
ypos1=0
ypos2=2
divy=5
subdivy=1
unity=1
x1=4.3066451e-06
x2=4.9079404e-06
divx=5
subdivx=1
xlabmag=1.0
ylabmag=1.0
node="clk_data
result;data[5],data[4],data[3],data[2],data[1],data[0]
start"
color="8 6 7"
dataset=-1
unitx=1
logx=0
logy=0
digital=1}
B 2 60 580 860 980 {flags=graph
y1=0.013
y2=1.5
ypos1=1.7
ypos2=1.9
divy=5
subdivy=4
unity=1
x1=4.3066451e-06
x2=4.9079404e-06
divx=5
subdivx=1
xlabmag=1.0
ylabmag=1.0


dataset=-1
unitx=1
logx=0
logy=0

digital=0


sim_type=tran


color="4 5"
node="x1.vdac_pi
x1.vdac_ni"}
N 360 -380 360 -360 {
lab=#net1}
N 440 -380 440 -360 {
lab=#net2}
N 520 -380 520 -360 {
lab=#net3}
N 280 -140 280 -120 {
lab=#net4}
N 460 -140 460 -120 {
lab=#net5}
C {devices/lab_wire.sym} 1280 -320 0 0 {name=p1 sig_type=std_logic lab=VDD}
C {devices/lab_wire.sym} 1280 -140 2 1 {name=p3 sig_type=std_logic lab=VSS}
C {devices/vsource.sym} 280 -330 0 0 {name=V1 value=\{VDD\} savecurrent=true}
C {devices/lab_wire.sym} 280 -300 2 1 {name=p11 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 280 -360 0 0 {name=p12 sig_type=std_logic lab=VDD}
C {devices/vsource.sym} 360 -330 0 0 {name=V2 value=\{VCM\} savecurrent=true}
C {devices/lab_wire.sym} 360 -300 2 1 {name=p13 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 360 -440 0 0 {name=p14 sig_type=std_logic lab=VCM}
C {devices/vsource.sym} 440 -330 0 0 {name=V3 value=\{VREF\} savecurrent=true}
C {devices/lab_wire.sym} 440 -300 2 1 {name=p15 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 440 -440 0 0 {name=p16 sig_type=std_logic lab=VREF}
C {devices/vsource.sym} 600 -330 0 0 {name=V4 value=0 savecurrent=false}
C {devices/lab_wire.sym} 600 -300 2 1 {name=p17 sig_type=std_logic lab=GND}
C {devices/lab_wire.sym} 600 -360 0 0 {name=p18 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 280 -60 2 1 {name=p19 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 280 -200 0 0 {name=p20 sig_type=std_logic lab=VIN_P}
C {devices/lab_wire.sym} 460 -60 2 1 {name=p21 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 460 -200 0 0 {name=p22 sig_type=std_logic lab=VIN_N}
C {devices/vsource.sym} 680 -90 0 0 {name=V7 value="pulse(0 \{VDD\} 20n 1n 1n 100n 1u)" savecurrent=false}
C {devices/lab_wire.sym} 680 -60 2 1 {name=p23 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 680 -120 0 0 {name=p24 sig_type=std_logic lab=START}
C {devices/vsource.sym} 680 -330 0 0 {name=V8 value="pwl(0 0 10n 0 10.1n \{VDD\})" savecurrent=false}
C {devices/lab_wire.sym} 680 -300 2 1 {name=p25 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 680 -360 0 0 {name=p26 sig_type=std_logic lab=RST_Z}
C {devices/code.sym} 50 -180 0 0 {name=TT_MODELS
only_toplevel=true
format="tcleval(@value )"
value="
* Skywater 130 nm PDK models
.lib $::SKYWATER_MODELS/sky130.lib.spice tt

* Models for standard digital cells
*.include $::SKYWATER_STDCELLS/sky130_fd_sc_hd.spice

* C extraction spice netlist for CDAC
*.include [xschem get current_dirname]/../layout/subcells/CDAC/CDAC_mim_12bit_flat.spice

* Spice netlist for state machine generated by openlane
*.include [xschem get current_dirname]/../layout/subcells/state_machine/state_machine_openlane_generated.spice

* C or RC extraction of the SAR ADC
.include [xschem get current_dirname]/../layout/SAR_ADC_12bit_flat.spice
"
spice_ignore=false
place=header}
C {devices/launcher.sym} 120 -460 0 0 {name=h2 
descr="Simulate" 
tclcommand="xschem netlist; xschem simulate"}
C {devices/code.sym} 43.58642578125 -375.07080078125 0 0 {name=NGSPICE
only_toplevel=true
value="
* Supply, common mode and reference voltage
.param VDD = 1.8
.param VREF = 1.2
.param VREF_GND = 0
.param VCM = 0.6

.option temp = 27

*.save all

* Control signals
.save start rst_z clk en_offset_cal

* Input signals
.save vin_p vin_n

* Reference, supply
.save vref vref_gnd vcm vdd

* Output signals
.save clk_data data[5] data[4] data[3] data[2] data[1] data[0]

* Internal signals
.save x1.vdac_p x1.vdac_n x1.vdac_pi x1.vdac_ni x1.smpl x1.en_comp x1.comp_p x1.comp_n x1.cal_p x1.cal_n
.save x1.en_vin_bstr_p x1.en_vin_bstr_n
.save x1.c10_p_btm x1.c9_p_btm x1.c8_p_btm x1.c7_p_btm x1.c6_p_btm x1.c5_p_btm x1.c4_p_btm x1.c3_p_btm x1.c2_p_btm x1.c1_p_btm x1.c0_p_btm x1.C0_dummy_p_btm
.save x1.c10_n_btm x1.c9_n_btm x1.c8_n_btm x1.c7_n_btm x1.c6_n_btm x1.c5_n_btm x1.c4_n_btm x1.c3_n_btm x1.c2_n_btm x1.c1_n_btm x1.c0_n_btm x1.C0_dummy_n_btm

.option GMIN=1e-12 reltol=1e-5
.control
		set ngbehavior=hsa
          		set skywaterpdk
          		set ng_nomodcheck
          		set num_threads=4
          		option noinit
          		option klu
		tran 10n 7u
		write top_level_differential_sim.raw
.endc
"}
C {devices/vsource.sym} 280 -90 0 0 {name=V5 value="pwl(0.000u 0.6 1u 0.6
+ 1.000u 0.4000 2u 0.4000
+ 2.001u 0.8000 3u 0.8000
+ 3.001u 0.9599 4u 0.9599
+ 4.001u 0.2401 5u 0.2401
+ 5.001u 0.0186 6u 0.0186
+ 6.001u 1.1814 7u 1.1814)" savecurrent=false}
C {../schematic/SAR_ADC_12bit.sym} 720 -320 0 0 {name=x1}
C {devices/res.sym} 360 -410 2 0 {name=R1
value=500
footprint=1206
device=resistor
m=1}
C {devices/vsource.sym} 680 -210 0 0 {name=V9 value="pulse(0 \{VDD\} 0 1n 1n 40n 50n)" savecurrent=false}
C {devices/lab_wire.sym} 680 -180 2 1 {name=p30 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 680 -240 0 0 {name=p31 sig_type=std_logic lab=CLK}
C {devices/lab_pin.sym} 1000 -240 0 0 {name=p37 lab=VIN_P}
C {devices/lab_pin.sym} 1000 -220 0 0 {name=p38 lab=VIN_N}
C {devices/lab_pin.sym} 1000 -280 0 0 {name=p39 lab=RST_Z}
C {devices/lab_pin.sym} 1340 -240 0 1 {name=p40 lab=CLK_DATA}
C {devices/lab_pin.sym} 1340 -220 0 1 {name=p41 lab=DATA[5:0]}
C {devices/lab_pin.sym} 1000 -260 0 0 {name=p42 lab=START}
C {devices/lab_pin.sym} 1000 -200 0 0 {name=p43 lab=EN_OFFSET_CAL}
C {devices/lab_pin.sym} 1000 -300 0 0 {name=p44 lab=CLK}
C {devices/lab_pin.sym} 1000 -180 0 0 {name=p46 lab=SINGLE_ENDED}
C {devices/lab_wire.sym} 1160 -140 2 1 {name=p33 sig_type=std_logic lab=VREF_GND}
C {devices/lab_wire.sym} 1200 -320 0 0 {name=p8 sig_type=std_logic lab=VCM}
C {devices/lab_wire.sym} 1160 -320 0 0 {name=p9 sig_type=std_logic lab=VREF}
C {devices/vsource.sym} 460 -90 0 0 {name=V6 value="pwl(0.000u 0.6 1u 0.6
+ 1.000u 0.8000 2u 0.8000
+ 2.001u 0.4000 3u 0.4000
+ 3.001u 0.2401 4u 0.2401
+ 4.001u 0.9599 5u 0.9599
+ 5.001u 1.1814 6u 1.1814
+ 6.001u 0.0186 7u 0.0186)" savecurrent=false}
C {devices/vsource.sym} 520 -330 0 0 {name=V10 value=\{VREF_GND\} savecurrent=true}
C {devices/lab_wire.sym} 520 -300 2 1 {name=p7 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 520 -440 0 0 {name=p10 sig_type=std_logic lab=VREF_GND}
C {devices/res.sym} 440 -410 2 0 {name=R6
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} 520 -410 2 0 {name=R7
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} 280 -170 2 0 {name=R8
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} 460 -170 2 0 {name=R9
value=500
footprint=1206
device=resistor
m=1}
C {devices/lab_wire.sym} 280 -520 2 1 {name=p2 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 280 -580 0 0 {name=p4 sig_type=std_logic lab=EN_OFFSET_CAL}
C {devices/vsource.sym} 280 -550 0 0 {name=V11 value="pwl(0 0 3u 0 3.001u \{VDD\})" savecurrent=false}
C {devices/lab_wire.sym} 520 -520 2 1 {name=p5 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 520 -580 0 0 {name=p6 sig_type=std_logic lab=SINGLE_ENDED}
C {devices/vsource.sym} 520 -550 0 0 {name=V12 value=0 savecurrent=false}
C {devices/launcher.sym} 130 120 0 0 {name=h5
descr="Load Waveforms" 
tclcommand="xschem raw_read $netlist_dir/top_level_differential_sim.raw tran"
}
